### ISSUE TITLE
Wide code blocks trick Gitiles into not line-wrapping README.md

### ISSUE THREAD

**Issue by ferdnyc** [google/gitiles#108]
Code blocks with very long lines can trick Gitiles into an extremely wide rendering of README.md on the project main page (only), forcing horizontal scrolling. 

See e.g. https://swiftshader.googlesource.com/SwiftShader/ (where I discovered this), which contains a code block of 208 characters in a single line.

This is in contrast to Gitiles' own rendering of the same file (https://swiftshader.googlesource.com/SwiftShader/+/master/README.md, or even its embedding at the bottom of https://swiftshader.googlesource.com/SwiftShader/+/master), where the file is wrapped to browser width, and the code block is set `overflow:scroll`. This seems like a more useful view of the content, so it would be helpful if the file was rendered the same way when displayed on the project root.

**Comment by cbd4feather** [comment]
https://swiftshader.google/outsource.com/SwiftShader/+/master

Try this one out

**Comment by ferdnyc** [comment]
@cbd4feather I'm confused, that appears to be a bad URL.
Were you intending to link to https://swiftshader.googlesource.com/SwiftShader/+/master ? If so, as I mentioned in my original report, the README.md renders fine there — it aways has.
> or even its embedding at the bottom of https://swiftshader.googlesource.com/SwiftShader/+/master), where the file is wrapped to browser width, and the code block is set `overflow:scroll`. 

It's only when the README.md is rendered at the project root https://swiftshader.googlesource.com/SwiftShader/  that it's not wrapped properly.

**Comment by cbd4feather** [comment]
Yes about correct format for my phone from some other reach IV been looking
at  you've got it down to as close to perfect as I can see

**Comment by ferdnyc** [comment]
It appears this was fixed at some point, as https://swiftshader.googlesource.com/SwiftShader/ is now wrapped normally.
