### ISSUE TITLE
Is anyone from the project reading this? — READ BEFORE OPENING NEW ISSUES

### ISSUE THREAD

**Issue by oberlies** [google/gitiles#113]
The Gitiles project is active - see https://gerrit.googlesource.com/gitiles/ - but there is no visible activity from any project members [here on Github](https://github.com/google/gitiles/issues).

Plus, the sources available here are (at the time of writing this) 9 months behind the master repository at googlesource.

So...
* Are the Gitiles project members planning to use GitHub at all?
* If this isn't [the issue tracker of Gitiles](https://groups.google.com/d/msg/repo-discuss/hkSq7vTUxsM/cLGV3oV6BwAJ), where is it then?

**Comment by jrn** [comment]
This is the issue tracker of gitiles.
