### ISSUE TITLE
"Chromium" text not correctly aligned to the Chromium logo

### ISSUE THREAD

**Issue by ChromiumLogoSpinner** [google/gitiles#126]
![chromium logo and text](https://user-images.githubusercontent.com/35157612/35593298-5cfecb84-05c4-11e8-9d71-f123b39e6100.PNG)

Example page: https://chromium.googlesource.com/chromium/src

The "Chromium" text is not correctly aligned to the Chromium logo in that it is aligned to the bottom of the Chromium logo when it should be aligned to the middle of the Chromium logo.

**Comment by jrn** [comment]
Gitiles is just a repository browser --- the Gitiles project does not control the content of the repositories you browse.

https://crbug.com/new would be more likely to reach the people you're trying to reach.
