### ISSUE TITLE
Gitiles log next/previous links don't work as expected

### ISSUE THREAD

**Issue by aarongable** [google/gitiles#128]
**What steps will reproduce the problem?**
- Go to https://chromium.googlesource.com/chromium/src
- See that it gives you a nice log of the five most recent commits
- Have a desire to see more than just the most recent five
- Click "Next >>"

**What is the expected output?**
- I get taken to a view of the most recent ~hundred commits

**What do you see instead?**
- I get taken to a view of *almost* the most recent hundred commits, but missing those five that were displayed on the first page

**What steps will reproduce the problem?**
- Click "<< Previous" to try to get a view containing those first five

**What is the expected result?**
- A view showing the ~hundred most recent commits

**What do you see instead?**
- It reloads the exact same page. It's impossible to see to those first five that were previewed without returning to the repo homepage.

**Comment by dborowitz** [comment]
> * I get taken to a view of the most recent ~hundred commits

IMHO, a link that says "Next" should not take you to a page that repeats the contents of the page you're currently looking at, and I am a little surprised that you expect it to. But that's just a reflection of the link text; I think it's actually fine behavior for the link from the repo index page to take you to a log starting from the tip. So I would be ok with your suggestion if we also change the text to say "More" or something.

**Comment by aarongable** [comment]
Absolutely agreed; I think the best fix for the first half of this bug is for the front page to have something like a "More" or "Log" link, rather than having the same "Next>>" link that full log pages have.

**Comment by dborowitz** [comment]
https://gerrit-review.googlesource.com/c/gitiles/+/158830

**Comment by aarongable** [comment]
I just noticed another issue with the next/previous links:

1. Go to any raw +log url, like https://chromium.googlesource.com/chromium/src/+log/
2. Click "Next >>"

Expected result: the next page of results
Actual result: a 404, because the url populates "null" instead of "HEAD"

**Comment by dborowitz** [comment]
Jeez, who knows how long that's been broken:
https://gerrit-review.googlesource.com/#/c/gitiles/+/158831

**Comment by aarongable** [comment]
Dang that was fast, you beat me to it. And your solution is better anyway. Thanks for finding those fixes so fast!

**Comment by jrn** [comment]
Fixed by https://gerrit.googlesource.com/gitiles/+/571b7a06e3e6b6bf0d11d6ee9e07050f762e7fbb and https://gerrit.googlesource.com/gitiles/+/fa80a6a768b509e10df00ee96f01573097250e20.
