### ISSUE TITLE
Support asciidoc in addition to markdown

### ISSUE THREAD

**Issue by alonbl** [google/gitiles#131]
Hi,
Asciidoc becomes more popular, it would be very nice if you render it using AsciiDoctor or any similar library. We have pressure to switch, and we will lose the nice browse of gitiles.
Thanks!

**Comment by hanwen** [comment]
asciidoctor shells out to ruby, AFAIK, so it's problematic for use with a Java system.

I think MarkDown is way more popular than AsciiDoc, so I don't see it becoming more popular soon.

**Comment by alonbl** [comment]
thanks! spring and all derived tools are switching, github already support asciidoc, also the x-doc gerrit plugin has some support, did not check as I prefer the gitiles mode.

**Comment by paladox** [comment]
Asciidoc is old, Asciidocter is the newer one. Gerrit uses that to generate it's doc.

**Comment by nattgris** [comment]
I'm not a Java person, but it seems Asciidoctor is supposed to be usable in a JVM:

https://github.com/asciidoctor/asciidoctorj

Also, the conversion can be made client side using Asciidoctor.js...

Would any of these options work for gitiles?

**Comment by jrn** [comment]
No plans for asciidoc support, for the reasons hanwen mentioned (security implications).

**Comment by nattgris** [comment]
Sorry, I don't see anyone mentioned security implications, or why they would be different compared to the existing Markdown rendering.
