### ISSUE TITLE
Header is broken on Markdown Doc

### ISSUE THREAD

**Issue by michaelblyons** [google/gitiles#162]
https://gerrit.googlesource.com/gitiles/+/HEAD/Documentation/markdown.md

![Screen Shot 2019-04-26 at 9 45 09 AM](https://user-images.githubusercontent.com/2701605/56811999-0423e880-6808-11e9-9b1e-d02b86ce14aa.png)

**Comment by agnosticdev** [comment]
I am also seeing the same thing: 
![markdown_error](https://user-images.githubusercontent.com/7466510/57621966-482a2380-7552-11e9-9814-31ef31b4864c.png)

**Comment by michaelblyons** [comment]
Guess this is fixed? Who knows when. 🤷
