### ISSUE TITLE
Gitiles crashes the JVM heap by allocating GBs of strings

### ISSUE THREAD

**Issue by lucamilanesio** [google/gitiles#192]
Given Gitiles 0.2-11 and a 100MBytes XML file to render, Gitiles uses GBs of memory and eventually crashes the JVM heap.

This is due to a misunderstanding in the `loader.getCachedBytes(MAX_FILE_SIZE)` JGIt behaviour: Gitiles thought that the method would have never returned content larger than MAX_FILE_SIZE, but instead JGit *would* return large content if that was cached in memory.

Eventually, attempting to render hundreds of GBytes of data, Gitiles would just crash.

**Comment by lucamilanesio** [comment]
Fix uploaded to [Gerrit-Review Change 246032](https://gerrit-review.googlesource.com/c/gitiles/+/246032)

**Comment by jrn** [comment]
Thanks, Luca!
