### ISSUE TITLE
Caching is not working in Android mobile chrome  browser even though added cachecontrol in IIS version-10 and also in XAMPP

### ISSUE THREAD

**Issue by vasanthhr** [google/gitiles#197]
I added cachecontrol in IIS and XAMPP, but caching works good in desktop, laptop ,other android mobile and safari browsers.

But caching not working in **Android mobile Chrome browser.**

Please guide me how to make  caching works in Android mobile chrome browser.

I added these config in web.config file as:

```
 <staticContent>
        <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="20.00:00:00" />
    </staticContent>

```

Also added in XAMP .htaccess file as below:

```
# cache: One month for these files
<filesMatch ".(css|js|wasm|xml)$">
Header set Cache-Control "max-age=2628000, public"
</filesMatch>
```

**Comment by jrn** [comment]
This is the bug tracker for Gitiles. Was this report meant as a report against Gitiles or Android?
