### ISSUE TITLE
Link to Chromium revisions when using rXXXXX syntax on commit descriptions

### ISSUE THREAD

**Issue by mrego** [google/gitiles#214]
For example this commit message mentions r784709 (without a link):
https://chromium.googlesource.com/chromium/src/+/918e6ac7f91936d84231cd51c42b3352313ec4d3

However in the bugtracker entry once that commit landed there's a link for r784709:
https://bugs.chromium.org/p/chromium/issues/detail?id=1128984#c3
The link points to that revision in Chromium:
https://chromium.googlesource.com/chromium/src/+/d142fa3b0b37b823fe2038828e90e597fe49cfee

I think it'd be nice to have links in the first case too.

I'm not sure if this could be added generically to gitiles or is some kind of configuration that should be done in https://chromium.googlesource.com/chromium/.

**Comment by jrn** [comment]
This is configurable indeed; feel free to file a request at https://bugs.chromium.org/p/chromium/issues/entry?template=Infra-Git to make it happen (sorry for the runaround).

**Comment by mrego** [comment]
Thanks, I've reported https://bugs.chromium.org/p/chromium/issues/detail?id=1145465
