### ISSUE TITLE
Gitiles does not render some markdown tables (in Chromium documentation)

### ISSUE THREAD

**Issue by ajperel** [google/gitiles#215]
Some, but not all tables are not rendered properly by Gitiles in Chromium documentation.

Looking at: 
https://chromium.googlesource.com/chromium/src.git/+/master/docs/initialize_blink_features.md#2_depends-on-the-status-of-a-base_feature

The |'s and -'s are shown as is rather than producing a table.

Compare with the preview pane of Chromium code search which does produce a table:
https://source.chromium.org/chromium/chromium/src/+/master:docs/initialize_blink_features.md

In Gitiles, other tables do show up properly. e.g. https://chromium.googlesource.com/chromium/src.git/+/master/docs/android_build_instructions.md#figuring-out-target_cpu is fine.

I haven't validated this in an independent markdown file, but the table that doesn't render in the Chromium documentation above is:

```
| |No status|`status:"test"`|`status:"experimental"`|`status:"stable"`|
|-|---------|-----------------|--------------------------|-------------------|
|`FEATURE_DISABLED_BY_DEFAULT`|Disabled everywhere|Blink feature is enabled for tests, or everywhere with `--enable-blink-test-features` [1]|Blink feature is enabled for tests, or everywhere with `--enable-experimental-web-platform-features` [1]|Blink feature is enabled everywhere [2]|
|`FEATURE_ENABLED_BY_DEFAULT`|Enabled everywhere|Enabled everywhere|Enabled everywhere|Enabled everywhere|
```

This was reported to Chromium as https://crbug.com/1144349

**Comment by haruzheng** [comment]
Hi

Maybe you can try it.
```markdown=
| | No status | `status:"test"` | `status:"experimental"` | `status:"stable"` |
|-|-----------|-----------------|-------------------------|-------------------|
| `FEATURE_DISABLED_BY_DEFAULT` | Disabled everywhere | Blink feature is enabled for tests, or everywhere with `--enable-blink-test-features` [1] | Blink feature is enabled for tests, or everywhere with `--enable-experimental-web-platform-features` [1] | Blink feature is enabled everywhere [2] |
| `FEATURE_ENABLED_BY_DEFAULT` | Enabled everywhere| Enabled everywhere | Enabled everywhere | Enabled everywhere |
```

**Comment by dmurph** [comment]
Looks fixed?

**Comment by ajperel** [comment]
Surprisingly it does. Will close.
