### ISSUE TITLE
HTTP 404 Error for +/refs/*/$BRANCH$

### ISSUE THREAD

**Issue by misilita** [google/gitiles#223]
[Environment: Gerrit 2.15.3 with Gitiles 2.15]

We have a repo that has 100+ branches and 100+ tags.
When we access it via the GERRIT UI "Branches"  tab, we get an HTTP404 error.
Observed for:
http://$GERRIT_URL$/plugins/gitiles/$REPO$/+/refs/heads/$BRANCH$
http://$GERRIT_URL$/plugins/gitiles/$REPO$/+/refs/tags/$BRANCH$

Other repos that have lesser no. of branches/tags have no problem with it.

However, if we remove the "refs/heads" (http://$GERRIT_URL$/plugins/gitiles/$REPO$/+/$BRANCH$) portion, gitiles is able to render it properly.

Modifying heapLimit, core.packed* settings in gerrit.config does not help.
Did not also find anything in the documentation for gitiles.config that could possibly help.

Are there any special setting that could be configured to resolve this?

**Comment by jjhud1979** [comment]
Location: /storage/emulated/0/Android/data/com.brisk.jpay/files

**Comment by jjhud1979** [comment]
- # :smiley:

_Sent from my LM-Q730 using my [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jjhud1979** [comment]
@misilita :joy:

_Sent from my LM-Q730 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by misilita** [comment]
We found the culprit.
Someone pushed a branch called "ref" to the remote causing the problem.
After deleting that branch, everything worked normal.

**Comment by jjhud1979** [comment]
Thanks for your help 🐱
