### ISSUE TITLE
some issue with RSA_method and EVP_PKEY_method

### ISSUE THREAD

**Issue by famgqi-Samuel** [google/gitiles#242]
I have been using openssl before, and now I want to change it to boringssl. During this process, I encountered some problems.
1、	Most of low-level is deprecated, like RSA_meth_set_priv_enc ,RSA_set_method, Are these deprecated because of using fips?
2、	And some EVP_PKEY_method is deprecated too. Like EVP_PKEY_meth_set_encrypt, EVP_PKEY_meth_set_decrypt. Is there no open custom encryption and decryption function?
3、	If I want to use my own customized encryption and decryption functions, what api function interface should I use?

**Comment by hanwen** [comment]
this issue is in the wrong repository.
