### ISSUE TITLE
Support "..." in logs viewer

### ISSUE THREAD

**Issue by spearce** [google/gitiles#29]
Originally reported on Google Code with ID 29
```
works: https://gerrit.googlesource.com/gerrit/+log/stable-2.6..master
404: https://gerrit.googlesource.com/gerrit/+log/stable-2.6...master

I'd expect "+log/foo...bar" to give the same output as "git log foo...bar".
```

Reported by `None` on 2013-04-26 13:57:48

**Comment by htthao** [comment]
Hi @spearce,
Is there any update on this?

**Comment by hanwen** [comment]
Hi there, 

we are not investing in Gitiles at the moment.

Also, even though some automated process is posting updates on behalf of @spearce ,  Shawn unfortunately isn't with us anymore. See https://sfconservancy.org/blog/2018/jan/30/shawn-pearce/ for more information.

**Comment by htthao** [comment]
I'm so sorry. He did very meaningful things.
Thanks for letting me know.
