### ISSUE TITLE
URL to download tar/zip archive of a project

### ISSUE THREAD

**Issue by spearce** [google/gitiles#3]
Originally reported on Google Code with ID 3
```
Support downloading a tar (or zip) archive of a revision, e.g. /+archive/revision.tar.gz
or /+archive/revision.zip to download a tgz or a zip.
```

Reported by `None` on 2012-11-11 15:21:18

**Comment by ORESoftware** [comment]
I am just looking for a url to download a zip file, something like this:

curl https://raw.githubusercontent.com/oresoftware/r2g/releases/1.1.2.zip

**Comment by anjupawaria** [comment]
@ORESoftware did you get how to download a zip file?

**Comment by concatime** [comment]
@anjupawaria why `.tar.gz` wouldn’t work for you?

**Comment by anjupawaria** [comment]
@concatime i was doing a minor mistake. i got it.
