### ISSUE TITLE
Documentation (even cursory/automatic) of the REST api would be awesome

### ISSUE THREAD

**Issue by spearce** [google/gitiles#52]
Originally reported on Google Code with ID 54
```
Even just a (hopefully automatic) enumeration of the API modes (+log, +diff, etc.),
their sub routes and the options they take (format=..., etc.) would be great.

I'm not sure how much real documentation is really necessary since gitiles is a fundamentally
read-only service, and so just poking around at the endpoints would be enough to discover
what they do.
```

Reported by `None` on 2014-06-12 15:52:29

**Comment by whesse** [comment]
The issue 47 in this issue tracker is not a duplicate of this issue.  What issue 47 is this a duplicate of?

I still cannot find documentation of the gitiles REST api.  For example, the +log endpoint has a limit parameter "n" and a start parameter "s" that should be set from the "next" entry of the previous page's last result. I could only find this out by looking at the gitiles source code at [gitiles]/java/com/google/gitiles/LogServlet.java.

Is there some documentation of the parameters to the REST endpoints besides the source code?

**Comment by ilmari-lauhakangas** [comment]
> The issue 47 in this issue tracker is not a duplicate of this issue. What issue 47 is this a duplicate of?
> 
> I still cannot find documentation of the gitiles REST api. For example, the +log endpoint has a limit parameter "n" and a start parameter "s" that should be set from the "next" entry of the previous page's last result. I could only find this out by looking at the gitiles source code at [gitiles]/java/com/google/gitiles/LogServlet.java.
> 
> Is there some documentation of the parameters to the REST endpoints besides the source code?

#46 is the dupe
